/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ok0y2YQQo0E
 */
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Card } from "@/components/ui/card"

export function Component() {
  return (
    <Card className="border-2 border-dashed border-zinc-200 dark:border-zinc-800 p-6 rounded-md w-full max-w-sm">
      <div className="flex flex-col items-center space-y-4">
        <svg
          className=" w-8 h-8 text-zinc-500 dark:text-zinc-400"
          fill="none"
          height="24"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
          viewBox="0 0 24 24"
          width="24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
          <polyline points="17 8 12 3 7 8" />
          <line x1="12" x2="12" y1="3" y2="15" />
        </svg>
        <span className="text-sm text-zinc-500 dark:text-zinc-400">Drag & Drop your files here</span>
        <span className="text-xs text-zinc-400 dark:text-zinc-500">or</span>
        <div className="flex items-center space-x-2">
          <Label className="cursor-pointer" htmlFor="file-upload">
            <Button variant="outline">Browse Files</Button>
          </Label>
          <Input className="hidden" id="file-upload" type="file" />
        </div>
      </div>
    </Card>
  )
}
